sudo: required
services:
    -docker

before_install:
    -docker build -t rahulravinair85/docker-react -f Dockerfile.dev .

script:
    -docker run rahulravinair85/docker-react npm run test -- -- coverage